[package]
name = "matrix_lib"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0"
license_file="LICENSE"
description = "easy to use library to operate on matrices"

[lib]
name = "matrix_lib"
path = "./src/lib.rs"
crate-type = ["lib"]

[dependencies]
num = "0.4.0"